### ISSUE TITLE
[question] Requesting an out of bounds page

### ISSUE THREAD

**Issue by Lansoweb** [zendframework/zend-expressive-hal#10]
It's not an issue but, with the current implementation, if you request page >2 (?page=2) and the collection has fewer pages, the generator returns the last valid page.

This behavior is intended or should we throw an OutOfBoundsException (or something like that)?

**Comment by weierophinney** [comment]
We should likely throw an `OutOfBoundsException` in such cases. Care to open a PR?

**Comment by Lansoweb** [comment]
Sure.
