### ISSUE TITLE
Paginating returns _page as string

### ISSUE THREAD

**Issue by Lansoweb** [zendframework/zend-expressive-hal#11]
When paginating (eg. /todo?page=2) the "_page" is returned as string not int.

### Code to reproduce the issue

```
curl -XGET http://localhost:8080/todo?page=2
```

### Expected results
```json
{
    "_total_items": 30,
    "_page": 2,
    "_page_count": 2,
}
```

### Actual results
```json
{
    "_total_items": 30,
    "_page": "2",
    "_page_count": 2,
}
```

Writing a PR and will submit soon.

**Comment by weierophinney** [comment]
Honestly, this is likely because all data from query string parameters are strings. I'm open to casting, though, and will evaluate #12.
