### ISSUE TITLE
[documentation] Typos on the online documentation

### ISSUE THREAD

**Issue by guillaumemaka** [zendframework/zend-expressive-hal#43]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-expressive-hal/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-hal/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

There are typos on the documentation page https://docs.zendframework.com/zend-expressive-hal/ 

- Issue and source code links
- composer installation package name

**Comment by Ocramius** [comment]
@guillaumemaka can you try editing those docs directly from this repository?
