### ISSUE TITLE
Generate a templated Link from Route

### ISSUE THREAD

**Issue by DominicDetta** [zendframework/zend-expressive-hal#58]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-hal/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-hal/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

As already explained in the [zend-expressive-hal post](https://discourse.zendframework.com/t/generate-templated-link-with-zend-expressive-hal/935)
I'm trying to generate a templated Link as defined by the [PSR-13](https://www.php-fig.org/psr/psr-13/#14-link-templates).

### Code to reproduce the issue

This is my actual routing configuration in the config/routes.php file:
```php
$app->get('/api/test/{id}',App\Handler\TestHandler::class,'api.test.get');
```

The code I use to generate the link:
```php
/* Code */
 $linkGenerator=$this->resourceGenerator
        ->getLinkGenerator();
$linkGenerator->templatedFromRoute(
                    'test',
                    $request,
                    'api.test.get'
                );
/* Code */
```
### Expected results

The json response that I expect is something similar to this:
```php
{
    "id": 1,
    "name": "Test",
    "_links": {
        "test": {
            "href": "http://localhost/expressive-test/public/api/test/{id}",
            "templated": true
        }
    }
}
```

### Actual results

This is the error that I obtain:
```php
Zend\Expressive\Router\Exception\RuntimeException raised in file D:\Sites\expressive-test\vendor\zendframework\zend-expressive-fastroute\src\FastRouteRouter.php line 299:
Message: Route `api.test.get` expects at least parameter values for [id], but received []
```

**Comment by marcguyer** [comment]
You need to add the placeholder(s) for the params in the route as the fourth argument. For example:

```php
$linkGenerator=$this->resourceGenerator
        ->getLinkGenerator();
$linkGenerator->templatedFromRoute(
                    'test',
                    $request,
                    'api.test.get',
                    ['id' => '{id}']
                );
```

**Comment by webimpress** [comment]
@DominicDetta is it your issue now resolved?

**Comment by DominicDetta** [comment]
Sorry to reply this late, but I was pretty busy.
I'm feeling pretty retarted because effectively as @marcguyer proposed the error disappears after passing the fourth argument but only if the constraints is removed:
`/api/test/{id}` instead of `/api/test/{id:\d+}`
